import PDFDocument from 'pdfkit';

export interface ReceiptPDFData {
  merchant: string;
  date: string;
  total: number;
  returnBy: string | null;
  warrantyEnds: string | null;
  imageUrl?: string;
  qrCodeDataUrl?: string;
}

export function generateReceiptPDF(data: ReceiptPDFData): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: 'A4',
    margins: {
      top: 50,
      bottom: 50,
      left: 50,
      right: 50
    }
  });

  const { merchant, date, total, returnBy, warrantyEnds, imageUrl, qrCodeDataUrl } = data;
  
  // Header with SlipSafe branding
  doc.fontSize(24)
     .fillColor('#4f46e5')
     .text('SlipSafe', { align: 'center' });
  
  doc.fontSize(12)
     .fillColor('#666')
     .text('Digital Receipt Verification', { align: 'center' });
  
  doc.moveDown(2);
  
  // Receipt Details Section
  doc.fontSize(16)
     .fillColor('#000')
     .text('Receipt Details', { underline: true });
  
  doc.moveDown(0.5);
  
  doc.fontSize(12)
     .fillColor('#333');
  
  // Merchant
  doc.text(`Merchant: `, { continued: true })
     .fillColor('#000')
     .text(merchant);
  
  doc.fillColor('#333');
  
  // Purchase Date
  doc.text(`Purchase Date: `, { continued: true })
     .fillColor('#000')
     .text(new Date(date).toLocaleDateString());
  
  doc.fillColor('#333');
  
  // Total Amount
  doc.text(`Total Amount: `, { continued: true })
     .fillColor('#000')
     .text(`$${total.toFixed(2)}`);
  
  doc.moveDown(2);
  
  // Important Deadlines Section
  doc.fontSize(16)
     .fillColor('#000')
     .text('Important Deadlines', { underline: true });
  
  doc.moveDown(0.5);
  
  doc.fontSize(12)
     .fillColor('#333');
  
  // Return Deadline
  doc.text(`Return By: `, { continued: true })
     .fillColor('#dc2626')
     .text(returnBy ? new Date(returnBy).toLocaleDateString() : 'Not set');
  
  doc.fillColor('#333');
  
  // Warranty Deadline
  doc.text(`Warranty Expires: `, { continued: true })
     .fillColor('#dc2626')
     .text(warrantyEnds ? new Date(warrantyEnds).toLocaleDateString() : 'Not set');
  
  doc.moveDown(2);
  
  // Receipt Image (if available)
  if (imageUrl) {
    try {
      doc.fontSize(16)
         .fillColor('#000')
         .text('Receipt Image', { underline: true });
      
      doc.moveDown(0.5);
      
      // Convert base64 data URL to Buffer if needed
      let imageSource: string | Buffer = imageUrl;
      if (imageUrl.startsWith('data:')) {
        const base64Data = imageUrl.split(',')[1];
        imageSource = Buffer.from(base64Data, 'base64');
      }
      
      // Embed receipt image (centered, max width 400px)
      doc.image(imageSource, {
        fit: [400, 500],
        align: 'center'
      });
      
      doc.moveDown(1);
    } catch (err) {
      console.error('Error embedding receipt image:', err);
      doc.fontSize(10)
         .fillColor('#666')
         .text('(Receipt image unavailable)', { align: 'center' });
      doc.moveDown(1);
    }
  }
  
  // QR Code for verification (if available)
  if (qrCodeDataUrl) {
    try {
      doc.fontSize(16)
         .fillColor('#000')
         .text('Verification Code', { underline: true });
      
      doc.moveDown(0.5);
      
      // Convert base64 data URL to Buffer if needed
      let qrSource: string | Buffer = qrCodeDataUrl;
      if (qrCodeDataUrl.startsWith('data:')) {
        const base64Data = qrCodeDataUrl.split(',')[1];
        qrSource = Buffer.from(base64Data, 'base64');
      }
      
      // Embed QR code image
      doc.image(qrSource, {
        fit: [150, 150],
        align: 'center'
      });
      
      doc.moveDown(0.5);
      
      doc.fontSize(10)
         .fillColor('#666')
         .text('Scan this code to verify your receipt', { align: 'center' });
    } catch (err) {
      console.error('Error embedding QR code:', err);
      doc.fontSize(10)
         .fillColor('#666')
         .text('(QR code verification available online)', { align: 'center' });
    }
  }
  
  // Footer
  doc.moveDown(2);
  doc.fontSize(8)
     .fillColor('#999')
     .text('Generated by SlipSafe - Digital Receipt Management System', { align: 'center' });
  
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' });
  
  // Note: Caller must call doc.end() after piping to response
  // Example: doc.pipe(res); doc.end();
  
  return doc;
}
